(ql:quickload "hunchentoot")
(ql:quickload "cl-who")
(ql:quickload "drakma")
(ql:quickload "parenscript")
(ql:quickload "parseq")
(ql:quickload "cacle")
(setq cl-who:*attribute-quote-char* #\")
(load "packages.lisp")
(load "test-handlers.lisp")
(load "script-engine.lisp")
(load "script.lisp")
(load "NAL-parser.cl")
(load "nal-functions.lisp")
(load "nal-page.lisp")
(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 8000))
